# Generated by Django 3.2.6 on 2023-03-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='gender',
            field=models.IntegerField(choices=[('0', 'Male'), ('1', 'Female')], default=1),
        ),
    ]
