# Generated by Django 3.2.6 on 2023-03-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0002_alter_visitors_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
    ]
