# Generated by Django 3.2.6 on 2023-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0003_alter_visitors_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
