# Generated by Django 3.2.6 on 2023-03-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0005_auto_20230325_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='qrstr',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
