# Generated by Django 3.2.6 on 2023-03-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0006_qrcodes_qrstr'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='photo',
            field=models.BinaryField(null=True),
        ),
    ]
